name: 'dependabot-usage-report'
description: 'Find all repos using dependabot'
inputs:
  token:
    description: 'A Personal Access token with admin:org scope'
    required: true
  org:
    description: 'Custom GitHub organization to retrieve data for'
    default: ${{ github.repository_owner }}
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
